global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'eol_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:2112']

rule_files:
  - rules/*.yml
